<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Coding standard
|--------------------------------------------------------------------------
|
| Hypervel's own config, `vendor/hypervel/components/.php-cs-fixer.php` on the
| 0.4 branch. Its rules are imported verbatim as .github/php-cs-fixer-rules.php,
| shared by every ipsocode/hypervel-* package; only this header, the finder and
| the cache file differ from it.
|
*/

use PhpCsFixer\Config;
use PhpCsFixer\Runner\Parallel\ParallelConfig;

$maxProcesses = function_exists('swoole_cpu_num') ? swoole_cpu_num() : 4;

return (new Config)
    ->setParallelConfig(new ParallelConfig($maxProcesses))
    ->setRiskyAllowed(true)
    ->setRules(require __DIR__ . '/.github/php-cs-fixer-rules.php')
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            // The Workbench application's runtime storage — gitignored, and
            // regenerated by the Testbench skeleton on every boot.
            ->exclude('workbench/storage')
            // The tools' caches.
            ->exclude('tests/.cache')
            ->in(__DIR__)
    )
    ->setCacheFile(__DIR__ . '/tests/.cache/php-cs-fixer.cache');
